# Путь до докер файла указываем относительно директории в build
nginx:
 dockerfile: ./Dockerfile
 build: ./contaners/nginx
 ports:
  - 8080:80
 volumes:
  - ./logs:/etc/logs/nginx
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=80
 command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
 links:
  - fpm

fpm:
 dockerfile: ./Dockerfile
 build: ./contaners/fpm
 ports:
 - 8083:9000
 environment:
  XDEBUG_CONFIG: "default_enable=0 remote_enable=1 remote_autostart=0 remote_connect_back=0 idekey=IDEAKEY remote_host=192.168.1.3 profiler_enable=0"
 volumes:
  - ./php-code:/var/www/html:rw
 links:
  - db

db:
 image: mariadb
 ports:
  - 8082:3306
 volumes:
  - ./database/mysql:/var/lib/mysql
 environment:
  MYSQL_DATABASE: docker-php
  MYSQL_USER: docker-php
  MYSQL_PASSWORD: docker-php-pass
  MYSQL_ROOT_PASSWORD: example

adminer:
 image: adminer
 ports:
  - 8081:8080
 links:
  - db
